### ISSUE TITLE
Investigate proper support for "build-for: all"

### ISSUE THREAD

**Issue by tigarmo** [canonical/snapcraft#4603]
### What needs to get done

We're (temporarily) disabling support for `build-for: all` in core24 because we need to revisit/investigate what a "correct" multiplatform snap looks like.

### Why it needs to get done

The feature as it is right now in core22 is not really "multi-platform"

**Comment by mr-cal** [comment]
We have decided not to support `build-for: all` in `core24` because of:
- Limited scenarios where snaps are truly architecture-independent. For example, Python-only scripts are becoming increasingly more architecture-dependent (i.e. the cryptography library).
- Limited scenarios where a separate snap for each architecture is not satisfactory
- Remote-build and snap store allow developers to build on all supported architectures

If any user stories for `build-for: all` in `core24` occur, create a new ticket for discussion.
