### ISSUE TITLE
Cacnel previous pending versions on new version uplaod

### ISSUE THREAD

**Issue by raivisdejus** [canonical/snapcraft#4844]
### What needs to get done

Our project uses GitHub actions to upload snaps to the store. During times of active development our snap upload action fails with error.
```
Issues while processing snap:
- Waiting for previous upload(s) to complete their review process. If you want to prioritize this last one, go to the other upload(s) page in https://dashboard.snapcraft.io/ and click on the 'Reject and remove from review queue' button.
```

When a new version is pushed to the snap, all previous versions are no longer relevant and their further review and validation is just a waist of resources as those versions are no longer "latest" and will not be used for anything.

I propose to implement a feature where on new version upload all pending versions would be cancelled.

If there are use cases where it is desirable to keep all versions, this new feature can be optional and could be invoked with some flag, like `snap upload --cancel-pending-reviews my-snap`

### Why it needs to get done

Review of snap versions that have been superseded by another is a waste of resources ans slows down release of snaps

**Comment by mr-cal** [comment]
@suligap - is there an API call to reject a pending snap?  I don't see anything obvious here https://dashboard.snapcraft.io/docs/reference/v1/snap.html

**Comment by raivisdejus** [comment]
Solution may also be some system process that cancels outdated versions and a change in upload logic to not throw error if some previous version is pending.

**Comment by suligap** [comment]
There's currently no way to reject an upload pending review via the API.

The store generally considers the error pasted above an exception that requires a manual intervention, ie. this error is only returned when any of the preceding uploads are in a blocked state, eg. require a manual review. If a review for the newest upload is not progressing because reviews for some preceding uploads are, the status API will return a being_processed response (no error).

**Comment by raivisdejus** [comment]
Clear, thanks for explanation
